### ISSUE TITLE
Add Rich-Presence-Mod

### ISSUE THREAD

**Issue by MenomDE** [TacticalTrainingTeam/ttt_a3#47]
Gerne würde ich für die bessere Sichtbarkeit des TTT wieder die RichPresenseMod integrieren, sodass im Discord (wer es aktiv hat) nicht nur zu sehen ist "Spielt Arma 3", sondern "Spielt Arma 3 mit dem TTT" inkl. Infos

Fürs nächste OM.

**Comment by Andx667** [comment]
Steam WS https://steamcommunity.com/sharedfiles/filedetails/?id=1493485159
Github https://gist.github.com/ConnorAU/b44448714e7ac46715d6959be8dd4240

alternative

Steam WS https://steamcommunity.com/sharedfiles/filedetails/?id=1326839989

**Comment by MenomDE** [comment]
https://github.com/TacticalTrainingTeam/Modmanagement/tree/7d0877dfe2646418b1c95ffd2b3c03fb9bfae7bc/%40Tactical_Training_Team/addons/ttt_discordRichPresence

**Comment by Andx667** [comment]
10s Updatezyklus fühlt sich ziemlich schnell an. Reicht da vllt nicht wenn wir 60s machen?
https://github.com/TacticalTrainingTeam/ttt_a3/tree/47-add-rich-presence-mod
